src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOfferRepository::class)]
class JobOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $activity = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $job_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $job_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $job_category = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $closing_date = null;

    #[ORM\Column(nullable: true)]
    private ?int $salary = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'jobOffer', targetEntity: Candidature::class)]
    private Collection $candidatures;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    private ?Client $client = null;

    public function __construct()
    {
        // $this->client = new ArrayCollection();
        $this->candidatures = new ArrayCollection(); 
    }

    public function __toString(): string
   {
        return $this->reference . '' . $this->job_title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isActivity(): ?bool
    {
        return $this->activity;
    }

    public function setActivity(?bool $activity): static
    {
        $this->activity = $activity;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(?string $job_title): static
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getJobType(): ?string
    {
        return $this->job_type;
    }

    public function setJobType(?string $job_type): static
    {
        $this->job_type = $job_type;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getJobCategory(): ?string
    {
        return $this->job_category;
    }

    public function setJobCategory(?string $job_category): static
    {
        $this->job_category = $job_category;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeImmutable
    {
        return $this->closing_date;
    }

    public function setClosingDate(?\DateTimeImmutable $closing_date): static
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(?int $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setJobOffer($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getJobOffer() === $this) {
                $candidature->setJobOffer(null);
            }
        }

        return $this;
    }
}

src/Form/JobOfferType.php
<?php

namespace App\Form;

use App\Entity\JobOffer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobOfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reference')
            ->add('description')
            ->add('activity')
            ->add('notes')
            ->add('job_title')
            ->add('job_type')
            ->add('location')
            ->add('job_category')
            ->add('closing_date')
            ->add('salary')
            ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => JobOffer::class,
        ]);
    }
}

src/Controller/JobOfferController.php
<?php

namespace App\Controller;

use App\Entity;
use App\Entity\Candidature;
use App\Entity\Candidat;
use App\Entity\JobOffer;
use App\Entity\User;
use App\Form\JobOfferType;
use App\Form\CandidatureType;
use App\Repository\CandidatureRepository;
use App\Repository\JobOfferRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/job/offer')]
class JobOfferController extends AbstractController
{
    #[Route('/', name: 'app_job_offer', methods: ['GET'])]
    public function index(JobOffer $jobOffer, JobOfferRepository $jobOfferRepository): Response
    {
        $jobOffers = $jobOfferRepository->findAll();

        return $this->render('job_offer/index.html.twig', [
            'job_offer' => $jobOffer,
            'job_offers' => $jobOffers,
        ]);
    }

    #[Route('/new', name: 'app_job_offer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $jobOffer = new JobOffer();
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($jobOffer);
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offer/new.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'app_job_offer_show', methods: ['GET'])] //defaults: ['id' => null])]
    public function show(JobOffer $jobOffer, JobOfferRepository $jobOfferRepository, CandidatureRepository $candidatureRepository, User $user): Response
    {
        /**
         * @var User $user
         */

        $user = $this->getUser();
        $candidat = $user->getCandidat();
        $candidature = $candidatureRepository->findOneBy([
            'user' => $user,
            'jobOffer' => $jobOffer
            ]);
    
        return $this->render('job_offer/show.html.twig', [
            'jobOffer' => $jobOffer,
            'joboffers' => $jobOfferRepository->findAll(),
            'candidature' => $candidature,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_job_offer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, JobOffer $jobOffer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offer/edit.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_job_offer_delete', methods: ['POST'])]
    public function delete(Request $request, JobOffer $jobOffer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jobOffer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($jobOffer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/job_offer/_delete_form.html.twig
<form method="post" action="{{ path('app_job_offer_delete', {'id': job_offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job_offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/job_offer/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/job_offer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit JobOffer{% endblock %}

{% block body %}
    <h1>Edit JobOffer</h1>

    {{ include('job_offer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_job_offer_index') }}">back to list</a>

    {{ include('job_offer/_delete_form.html.twig') }}
{% endblock %}

templates/job_offer/index.html.twig
{% extends 'base.html.twig' %}

{% block head %}{% endblock %}

{% block title %}Luxury Services recruitment & services
{% endblock %}

{% block body %}
	<div
		class="page">

		<!-- Page Header-->
		<section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h2 class="white-text">Our job offers</h2>
						<span class="white-text">Search and filter by job category</span>

					</div>
				</div>
			</div>
		</section>

		<!-- Page Content-->
		<section id="job-offers" class="section-padding gray-bg">
			<div class="container">
				<div class="text-center mb-40">
					<h2 class="section-title">We have the perfect job for you</h2>
					<p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
				</div>
				<div class="portfolio-container">

					<ul class="portfolio-filter brand-filter text-center">
						<li class="active waves-effect waves-light" data-group="all">All</li>
						<li class=" waves-effect waves-light" data-group="commercial">Commercial</li>
						<li class=" waves-effect waves-light" data-group="retail">Retail sales</li>
						<li class=" waves-effect waves-light" data-group="creative">Creative</li>
						<li class=" waves-effect waves-light" data-group="technology">Technology</li>
						<li class=" waves-effect waves-light" data-group="marketing">Marketing & PR</li>
						<li class=" waves-effect waves-light" data-group="fashion">Fashion & luxury</li>
						<li class=" waves-effect waves-light" data-group="management">Management & HR</li>
					</ul>
					<div class="portfolio portfolio-with-title col-2 gutter mt-30">

						<div class="portfolio-item" data-groups='["all", "commercial"]'>
							<div class="portfolio-wrapper">
								{% for joboffer in job_offers %}
									<div class="card job-card">
										<div class="card-content">
											<span class="title">
												<span class="card-title">{{ joboffer.JobTitle}}</span>
												<span class="ref grey-text">{{ joboffer.reference}}</span>
											</span>

											<div class="metas mb-20">
												<div class="meta">
													<i class="material-icons">&#xE53E;</i>
													{{ joboffer.salary }}&euro;
												</div>
												<div class="meta">
													<i class="material-icons">&#xE916;</i>2018-2020
												</div>
												<div class="meta">
													<i class="material-icons">&#xE55F;</i>
													{{ joboffer.location }}
												</div>
											</div>
											<p class="truncate-text">{{ joboffer.description }}</p>
										</div>

										<div class="card-action">
											<a class="btn btn-md primary border waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': joboffer.id}) }}">Details</a>
											<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
										</div>
									</div>
								{% endfor %}

							</div>
						</div>
						<div class="no-item"></div>
					</div>
				</div>
			</div>
		</section>

		<section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
			<div class="container">
				<div class="row">
					<div class="valign-wrapper text-center">
						<div class="hero-intro valign-cell">
							<h2 class="tt-headline clip is-full-width no-margin">
								<span>You are
								</span>
								<span class="tt-words-wrapper">
									<b class="is-visible">Commercial</b>
									<b>Creative</b>
									<b>Marketing & PR</b>
									<b>Technology</b>
									<b>Fashion & luxury</b>
									<b>Retail sales</b>
								</span>
							</h2>
							<h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
							<p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

							<a href="/register.html" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
						</div>
					</div>
				</div>
			</div>
		</section>

	</div>

</div>{% endblock %}

templates/job_offer/jobs.html.twig
{% extends 'base.html.twig' %}

{% block head %}{% endblock %}

{% block title %}Luxury Services recruitment & services
{% endblock %}

{% block body %}
	<div
		class="page">

		<!-- Page Header-->
		<section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h2 class="white-text">Our job offers</h2>
						<span class="white-text">Search and filter by job category</span>

					</div>
				</div>
			</div>
		</section>

		<!-- Page Content-->
		<section id="job-offers" class="section-padding gray-bg">
			<div class="container">
				<div class="text-center mb-40">
					<h2 class="section-title">We have the perfect job for you</h2>
					<p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
				</div>
				<div class="portfolio-container">

					<ul class="portfolio-filter brand-filter text-center">
						<li class="active waves-effect waves-light" data-group="all">All</li>
						<li class=" waves-effect waves-light" data-group="commercial">Commercial</li>
						<li class=" waves-effect waves-light" data-group="retail">Retail sales</li>
						<li class=" waves-effect waves-light" data-group="creative">Creative</li>
						<li class=" waves-effect waves-light" data-group="technology">Technology</li>
						<li class=" waves-effect waves-light" data-group="marketing">Marketing & PR</li>
						<li class=" waves-effect waves-light" data-group="fashion">Fashion & luxury</li>
						<li class=" waves-effect waves-light" data-group="management">Management & HR</li>
					</ul>
					<div class="portfolio portfolio-with-title col-2 gutter mt-30">

						<div class="portfolio-item" data-groups='["all", "commercial"]'>
							<div class="portfolio-wrapper">
								<div class="card job-card">
									<div class="card-content">
										<span class="title">
											<span class="card-title">2nd assistant position</span>
											<span class="ref grey-text">Ref. 1062</span>
										</span>
										<div class="metas mb-20">
											<div class="meta">
												<i class="material-icons">&#xE53E;</i>45k&euro;
											</div>
											<div class="meta">
												<i class="material-icons">&#xE916;</i>2018-10-01
											</div>
											<div class="meta">
												<i class="material-icons">&#xE55F;</i>Paris
											</div>
										</div>
										<p class="truncate-text">Nulla interdum, erat et mollis eleifend, urna turpis pellentesque dolor, sed rhoncus erat est sit amet diam. Aliquam dignissim ipsum nec lorem pulvinar.</p>
									</div>
									<div class="card-action">
										<a class="btn btn-md primary border waves-effect waves-dark" href="/jobs/show.html">Details</a>
										<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
									</div>
								</div>
							</div>
						</div>
						<div class="portfolio-item" data-groups='["all", "commercial"]'>
							<div class="portfolio-wrapper">
								<div class="card job-card">
									<div class="card-content">
										<span class="title">
											<span class="card-title">2nd assistant position</span>
											<span class="ref grey-text">Ref. 1062</span>
										</span>
										<div class="metas mb-20">
											<div class="meta">
												<i class="material-icons">&#xE53E;</i>45k&euro;
											</div>
											<div class="meta">
												<i class="material-icons">&#xE916;</i>2018-10-01
											</div>
											<div class="meta">
												<i class="material-icons">&#xE55F;</i>Paris
											</div>
										</div>
										<p class="truncate-text">Nulla interdum, erat et mollis eleifend, urna turpis pellentesque dolor, sed rhoncus erat est sit amet diam. Aliquam dignissim ipsum nec lorem pulvinar.</p>
									</div>
									<div class="card-action">
										<a class="btn btn-md primary border waves-effect waves-dark" href="/jobs/show.html">Details</a>
										<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
									</div>
								</div>
							</div>
						</div>
						<div class="portfolio-item" data-groups='["all", "commercial"]'>
							<div class="portfolio-wrapper">
								<div class="card job-card">
									<div class="card-content">
										<span class="title">
											<span class="card-title">2nd assistant position</span>
											<span class="ref grey-text">Ref. 1062</span>
										</span>
										<div class="metas mb-20">
											<div class="meta">
												<i class="material-icons">&#xE53E;</i>45k&euro;
											</div>
											<div class="meta">
												<i class="material-icons">&#xE916;</i>2018-10-01
											</div>
											<div class="meta">
												<i class="material-icons">&#xE55F;</i>Paris
											</div>
										</div>
										<p class="truncate-text">Nulla interdum, erat et mollis eleifend, urna turpis pellentesque dolor, sed rhoncus erat est sit amet diam. Aliquam dignissim ipsum nec lorem pulvinar.</p>
									</div>
									<div class="card-action">
										<a class="btn btn-md primary border waves-effect waves-dark" href="/jobs/show.html">Details</a>
										<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
									</div>
								</div>
							</div>
						</div>
						<div class="portfolio-item" data-groups='["all", "commercial"]'>
							<div class="portfolio-wrapper">
								<div class="card job-card">
									<div class="card-content">
										<span class="title">
											<span class="card-title">2nd assistant position</span>
											<span class="ref grey-text">Ref. 1062</span>
										</span>
										<div class="metas mb-20">
											<div class="meta">
												<i class="material-icons">&#xE53E;</i>45k&euro;
											</div>
											<div class="meta">
												<i class="material-icons">&#xE916;</i>2018-10-01
											</div>
											<div class="meta">
												<i class="material-icons">&#xE55F;</i>Paris
											</div>
										</div>
										<p class="truncate-text">Nulla interdum, erat et mollis eleifend, urna turpis pellentesque dolor, sed rhoncus erat est sit amet diam. Aliquam dignissim ipsum nec lorem pulvinar.</p>
									</div>
									<div class="card-action">
										<a class="btn btn-md primary border waves-effect waves-dark" href="/jobs/show.html">Details</a>
										<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
									</div>
								</div>
							</div>
						</div>
						<div class="no-item"></div>
					</div>
				</div>
			</div>
		</section>

		<section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
			<div class="container">
				<div class="row">
					<div class="valign-wrapper text-center">
						<div class="hero-intro valign-cell">
							<h2 class="tt-headline clip is-full-width no-margin">
								<span>You are
								</span>
								<span class="tt-words-wrapper">
									<b class="is-visible">Commercial</b>
									<b>Creative</b>
									<b>Marketing & PR</b>
									<b>Technology</b>
									<b>Fashion & luxury</b>
									<b>Retail sales</b>
								</span>
							</h2>
							<h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
							<p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

							<a href="/register.html" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
						</div>
					</div>
				</div>
			</div>
		</section>

	</div>

</div>{% endblock %}

templates/job_offer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New JobOffer{% endblock %}

{% block body %}
    <h1>Create new JobOffer</h1>

    {{ include('job_offer/_form.html.twig') }}

    <a href="{{ path('app_job_offer_index') }}">back to list</a>
{% endblock %}

templates/job_offer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}JobOffer
{% endblock %}

{% block body %}
	<div
		class="base">

		<!-- Page -->
		<div
			class="page">

			<!-- Page Header-->
			<section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h2 class="white-text">{{ jobOffer.jobTitle }}</h2>
							<span class="white-text">{{ jobOffer.reference }}</span>
							<ol class="breadcrumb">
								<li>
									<div class="portfolio-nav">
										<a href="#!" class="waves-effect waves-dark">
											<i class="fa fa-angle-left" aria-hidden="true"></i>
											Prev</a>
										<a href="#!" class="waves-effect waves-dark">
											<i class="fa fa-th-large" aria-hidden="true"></i>
										</a>
										<a href="#!" class="waves-effect waves-dark">Next
											<i class="fa fa-angle-right" aria-hidden="true"></i>
										</a>
									</div>
								</li>
							</ol>
						</div>
					</div>
				</div>
			</section>

			<!-- Page Content-->
			<section class="single-project-section section-padding light-gray-bg">
				<div class="container">
					<div class="project-overview">
						<div class="row mb-80">
							<div class="col-xs-12 col-md-8">
								<p class="ref grey-text no-margin">{{ jobOffer.reference }}</p>
								<h2>{{ jobOffer.jobTitle }}</h2>
								<p>{{ jobOffer.description}}</p>

							</div>

							<div class="col-xs-12 col-md-4 quick-overview">
								<ul class="portfolio-meta">
									<li>
										<span>
											Pulished at
										</span>24 May 18</li>
									<li>
										<span>
											Position
										</span>
										{{ jobOffer.jobTitle }}</li>
									<li>
										<span>
											Contract Type
										</span>
										{{ jobOffer.jobType }}</li>
									<li>
										<span>
											Salary
										</span>
										{{ jobOffer.salary }}
										&euro;</li>
									<li>
										<span>
											Location
										</span>
										{{ jobOffer.location}}</li>
									<li>
										<span>
											Starting date
										</span>2018-05-18</li>
								</ul>
								{% if is_granted('ROLE_USER') %}
									{% if candidature %}
										<div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">You have applied for this job</div>
									{% else %}
										<a class="btn btn-block gradient primary mt-30 waves-effect waves-light" href="{{ path('app_candidature_new', {'id': jobOffer.id}) }}">Apply for this job</a>
									{% endif %}
								{% else %}
									<a class="btn btn-block gradient primary mt-30 waves-effect waves-light" href="{{ path('app_login') }}">You have to be logged in</a>
								{% endif %}

							</div>
						</div>
					</div>

					<nav class="single-post-navigation no-margin" role="navigation">
						<div class="row">

							<div class="col-xs-6 col-sm-6 col-md-4">
								<div class="previous-post-link">
									<a class="btn border primary waves-effect waves-dark" href="#!">
										<i class="fa fa-long-arrow-left"></i>Previous
									</a>
								</div>
							</div>
							<div class="hidden-xs hidden-sm col-md-4"></div>


							<div class="col-xs-6 col-sm-6 col-md-4">
								<div class="next-post-link">
									<a class="btn border primary waves-effect waves-dark" href="#!">
										Next
										<i class="fa fa-long-arrow-right"></i>
									</a>
								</div>
							</div>
						</div>
					</nav>
				</div>
			</section>
		</div>
	</div>
{% endblock %}