src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatRepository::class)]
class Candidat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adress = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nationality = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $passport_file = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cv = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profil_picture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $current_location = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $date_of_birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $place_of_birth = null;

    #[ORM\Column(nullable: true)]
    private ?bool $availability = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $job_category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $experience = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $note = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $deleted_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $files = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $role = null;

    #[ORM\OneToOne(inversedBy: 'candidat', cascade: ['persist', 'remove'])]
    private ?User $id_user = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Candidature::class)]
    private Collection $candidatures;



    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): static
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getPassportFile(): ?string
    {
        return $this->passport_file;
    }

    public function setPassportFile(?string $passport_file): static
    {
        $this->passport_file = $passport_file;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): static
    {
        $this->cv = $cv;

        return $this;
    }

    public function getProfilPicture(): ?string
    {
        return $this->profil_picture;
    }

    public function setProfilPicture(?string $profil_picture): static
    {
        $this->profil_picture = $profil_picture;

        return $this;
    }

    public function getCurrentLocation(): ?string
    {
        return $this->current_location;
    }

    public function setCurrentLocation(?string $current_location): static
    {
        $this->current_location = $current_location;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeImmutable
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTimeImmutable $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPlaceOfBirth(): ?string
    {
        return $this->place_of_birth;
    }

    public function setPlaceOfBirth(?string $place_of_birth): static
    {
        $this->place_of_birth = $place_of_birth;

        return $this;
    }

    public function isAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(?bool $availability): static
    {
        $this->availability = $availability;

        return $this;
    }

    public function getJobCategory(): ?string
    {
        return $this->job_category;
    }

    public function setJobCategory(?string $job_category): static
    {
        $this->job_category = $job_category;

        return $this;
    }

    public function getExperience(): ?string
    {
        return $this->experience;
    }

    public function setExperience(?string $experience): static
    {
        $this->experience = $experience;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getFiles(): ?string
    {
        return $this->files;
    }

    public function setFiles(?string $files): static
    {
        $this->files = $files;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setUser($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getUser() === $this) {
                $candidature->setUser(null);
            }
        }

        return $this;
    }

}

src/Form/CandidatType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\HtmlSanitizer\Type\TextTypeHtmlSanitizerExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Male' => 'male',
                    'Female' => 'female',
                    'Non-binary' => 'non-binary',
                    'Transgender' => 'transgender',
                    'Genderqueer' => 'genderqueer',
                    'Genderfluid' => 'genderfluid',
                    'Agender' => 'agender',
                    'Bigender' => 'bigender',
                    'Two-spirit' => 'two-spirit',
                    'Androgyne' => 'androgyne',
                    'Pangender' => 'pangender',
                    'Demigender' => 'demigender',
                    'Intersex' => 'intersex',
                    'Cisgender' => 'cisgender',
                ],
            ])
            ->add('firstname')
            ->add('lastname')
            ->add('adress')
            ->add('country')
            ->add('nationality')
            ->add('passport_file', FileType::class,  [
                'data_class' => null,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'id' => 'passport',
                    'size' => '20000000',
                    'accpet' => '.pdf,.jpg,.doc,.docx,.png,.gif',
                    'name' => 'passport',
                    'type' => 'file',

                ]
            ])
            ->add('cv', FileType::class, [
                'data_class' => null,
                'mapped' => false,
                'required' => false,
                'attr' => [
                'id' => 'cv',
                'size' => 20000000,
                'accept' => '.pdf,.jpg,.doc,.docx,.png',
                'name' => 'cv',
                'type' => 'file',

                ]
            ])
            ->add('profil_picture', FileType::class, [
                'data_class' => null,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'id' => 'photo',
                    'size' => '20000000',
                    'accpet' => '.pdf,.jpg,.doc,.docx,.png,.gif',
                    'name' => 'photo',
                    'type' => 'file',
                ],
            ])
            ->add('current_location')
            ->add('date_of_birth')
            ->add('place_of_birth')
            ->add('availability')
            ->add('job_category', ChoiceType::class, [
                'choices' => [
                    'sectorA' => 'SectorA',
                    'sectorB' => 'SectorB',
                ],
            ])
            ->add('experience', ChoiceType::class, [
                'choices' => [
                    '0 - 6 month' => '3m',
                    '6 months - 1 year' => '6m',
                    '1 - 2 years' => '1y',
                    '2+ years' => '2y',
                    '5+ years' => '5y',
                    '10 years' => '10y'
                ],
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                'id' => 'description',
                'class' => 'materialize-textarea',
                'name' => 'description',
                'cols' => '50',
                'row' => '10'
                ],
                'label' => 'Short description for your profile, as well as more personnal informations (e.g. your hobbies/interests ). You can also paste any link you want.'
            ]);
            // ->add('note')
            // ->add('files');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

// use App\Entity\Candidat;

use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

#[Route('/candidat')]
class CandidatController extends AbstractController
{

    #[Route('/profile', name: 'app_candidat_profile', methods: ['GET', 'POST'])]
    public function edit(Request $request, EntityManagerInterface $entityManager): Response
    {   

        $candidat = $this->getUser()->getCandidat();
        // dd($candidat);

        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //upload profil pic
            if ($form['profil_picture']->getData()) { 
            /** @var UploadedFile $brochureFile */
                $profilePictureFile = $form['profil_picture']->getData();

                $profilPictureName = Uuid::v7();
                $extension = $profilePictureFile->guessExtension();
                if(!$extension) {
                    $extension = 'png';
                }

                $profilPictureName = $profilPictureName.'.'.$extension;
                $profilePictureFile->move('assets/uploads/', $profilePictureFile->getClientOriginalName());

                $candidat->setProfilPicture($profilPictureName);
                $entityManager->persist($candidat);
            }

            if ($form['passport_file']->getData()) { 
                /** @var UploadedFile $brochureFile */
                    $passportFile = $form['passport_file']->getData();
    
                    $passportName = Uuid::v7();
                    $extension = $passportFile->guessExtension();
                    if(!$extension) {
                        $extension = 'png';
                    }
    
                    $passportName = $passportName.'.'.$extension;
                    $passportFile->move('assets/uploads/passport', $passportFile->getClientOriginalName());
    
                    $candidat->setPassportFile($passportName);
                    $entityManager->persist($candidat);
                }

                if ($form['cv']->getData()) { 
                    /** @var UploadedFile $brochureFile */
                        $cvFile = $form['cv']->getData();
        
                        $cvName = Uuid::v7();
                        $extension = $cvFile->guessExtension();
                        if(!$extension) {
                            $extension = 'png';
                        }
        
                        $cvName = $cvName.'.'.$extension;
                        $cvFile->move('assets/uploads/passport', $cvFile->getClientOriginalName());
        
                        $candidat->setCv($cvName);
                        $entityManager->persist($candidat);
                    }

            $entityManager->persist($candidat);
            $entityManager->flush();

            return $this->redirectToRoute('app_candidat_profile', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('candidat/profile.html.twig', [
            'candidat' => $candidat,
            'formProfile' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_candidat_delete', methods: ['POST', 'GET'])]

    public function delete(Request $request, EntityManagerInterface $entityManager, Candidat $candidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $entityManager->remove($candidat);
            $entityManager->flush();
        }
    
        return $this->redirectToRoute('app_candidat_profile', [], Response::HTTP_SEE_OTHER);
    }
}

templates/candidat/_delete_form.html.twig
<form method="post" action="{{ path('app_candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidat/_form.html.twig
{{ form_start(formProfile) }}

<section class="section-padding">
	<div class="container">
		<div class="row">
			<h3 class="text-extrabold">Your personal information</h3>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_label(formProfile.gender) }}
					{{ form_widget(formProfile.gender) }}
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_label(formProfile.firstname) }}
					{{ form_widget(formProfile.firstname) }}
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_label(formProfile.lastname)}}
					{{ form_widget(formProfile.lastname)}}
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_label(formProfile.current_location)}}
					{{ form_widget(formProfile.current_location)}}
				</div>
			</div>

			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="input-field">
					{{ form_label(formProfile.adress)}}
					{{ form_widget(formProfile.adress)}}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="file-field input-field" style="margin-top: 32px;">
					<div class="btn btn-lg primary waves-effect waves-light">
						<span>
							<i class="material-icons">insert_photo</i>
							Photo</span>
						{{ form_label(formProfile.profil_picture)}}
						{{ form_widget(formProfile.profil_picture)}}
					</div>

					{% if candidat.profilPicture %}
					<div class="existing-file">
						<a href="{{ asset('assets/uploads/') }}" target="_blank">
							<i class="material-icons">&#xE24D;</i>
							Profil Picture</a>
					</div>
					<div class="file-path-wrapper">
						<input class="file-path validate" type="text" placeholder="Upload your ID photo" readonly>
					</div>
					{% endif %}
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-8">
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_label(formProfile.country)}}
							{{ form_widget(formProfile.country)}}
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_label(formProfile.nationality)}}
							{{ form_widget(formProfile.nationality)}}
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_label(formProfile.date_of_birth)}}
							{{ form_widget(formProfile.date_of_birth)}}
						</div>
					</div>
					<div class="col-xs-12 col-sm-6">
						<div class="input-field">
							{{ form_label(formProfile.place_of_birth)}}
							{{ form_widget(formProfile.place_of_birth)}}
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row mt-40">
			<h3 class="text-extrabold">Your professional profile</h3>
			<div class="col-xs-12 col-sm-6">
				<div class="card card-panel passport">
					<div class="file-field input-field">
						<div class="btn btn-lg primary waves-effect waves-light">
							<span>
								<i class="material-icons">&#xE24D;</i>
								Passport</span>
							{{ form_label(formProfile.passport_file)}}
							{{ form_widget(formProfile.passport_file)}}
						</div>
						<div class="existing-file">
							<a href="#!" target="_blank">
								<i class="material-icons">&#xE24D;</i>
								passeport.jpg</a>
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text" placeholder="Upload your passport" readonly>
						</div>
					</div>
					<div class="file-field input-field">
						<div class="btn btn-lg primary waves-effect waves-light">
							<span>
								<i class="material-icons">&#xE24D;</i>
								CV</span>
							{{ form_label(formProfile.cv)}}
							{{ form_widget(formProfile.cv)}}
						</div>

						<div class="existing-file">
							<a href="#!" target="_blank">
								<i class="material-icons">&#xE24D;</i>
								CV.pdf</a>
						</div>
						<div class="file-path-wrapper">
							<input class="file-path validate" type="text" placeholder="Upload your Curriculum Vitae" readonly>
						</div>
					</div>

				</div>
			</div>
			<div class="col-xs-12 col-sm-6">
				<div class="col-xs-12 col-sm-12">
					<div class="input-field" style="margin-top: 5px;">
						{{ form_label(formProfile.job_category)}}
						{{ form_widget(formProfile.job_category)}}
						<label for="job_sector" class="active">Interest in job sector</label>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12">
					<div class="input-field">
						{{ form_label(formProfile.experience)}}
						{{ form_widget(formProfile.experience)}}
						<label for="experience" class="active">Experience</label>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12">
				<div class="input-field">
					{{ form_label(formProfile.description)}}
					{{ form_widget(formProfile.description)}}
				</div>
			</div>
		</div>
	</div>
</section>

            <section class="section-padding gray-bg">
                <div class="container">
                    <div class="row">
                        <h3 class="text-extrabold">Your K-Yachting account</h3>
                        <div class="col-xs-12 col-sm-4">
                            <div class="input-field">
                                <input required="required" id="email" name="email" type="email" value="">
                                <label for="email">Email</label>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <div class="input-field">
                                <input id="password" name="password" type="password" value="">
                                <label for="password">Change your password here</label>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <div class="input-field">
                                <input id="password_repeat" name="password_repeat" type="password" value="">
                                <label for="password_repeat">Confirm your new password</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 mt-40 mb-80 delete-account">
                            <a href="app_candidat_delete" onclick="return prompt('Please Type \'Delete my account\' to delete your K-Yachting Services account:') == 'Delete my account'" class="btn btn-block btn-lg waves-effect waves-light"><i class="material-icons">&#xE872;</i>Delete my account</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <a href="#!" class="btn btn-block btn-lg border primary waves-effect waves-light"><i class="fa fa-long-arrow-left"></i> Back home</a>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-4">
                            <button type="submit" class="btn btn-block btn-lg gradient secondary waves-effect waves-light">
                                <span><strong>UPDATE</strong> NOW</span>
                            </button>
                        </div>
                    </div>

                </div>
            </section>

{{ form_end(formProfile) }}

templates/candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidat{% endblock %}

{% block body %}
    <h1>Edit Candidat</h1>

    {{ include('candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_candidat_index') }}">back to list</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}

templates/candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidat{% endblock %}

{% block body %}
    <h1>Create new Candidat</h1>

    {{ include('candidat/_form.html.twig') }}

    <a href="{{ path('app_candidat_index') }}">back to list</a>
{% endblock %}

templates/candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat{% endblock %}

{% block body %}
    <h1>Candidat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidat.id }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ candidat.gender }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ candidat.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ candidat.lastname }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ candidat.adress }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ candidat.country }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ candidat.nationality }}</td>
            </tr>
            <tr>
                <th>Passport_file</th>
                <td>{{ candidat.passportFile }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                <td>{{ candidat.cv }}</td>
            </tr>
            <tr>
                <th>Profil_picture</th>
                <td>{{ candidat.profilPicture }}</td>
            </tr>
            <tr>
                <th>Current_location</th>
                <td>{{ candidat.currentLocation }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ candidat.dateOfBirth ? candidat.dateOfBirth|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Place_of_birth</th>
                <td>{{ candidat.placeOfBirth }}</td>
            </tr>
            <tr>
                <th>Availability</th>
                <td>{{ candidat.availability ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Job_category</th>
                <td>{{ candidat.jobCategory }}</td>
            </tr>
            <tr>
                <th>Experience</th>
                <td>{{ candidat.experience }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ candidat.description }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ candidat.note }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ candidat.createdAt ? candidat.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ candidat.updatedAt ? candidat.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ candidat.deletedAt ? candidat.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Files</th>
                <td>{{ candidat.files }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ candidat.role }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_candidat_index') }}">back to list</a>

    <a href="{{ path('app_candidat_edit', {'id': candidat.id}) }}">edit</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}